require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Core::ApplicationsController do

  # This should return the minimal set of attributes required to create a valid
  # Core::Application. As you add validations to Core::Application, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { name: "foo_bar" }
  end

  describe "GET index" do
    it "assigns all core_applications as @core_applications" do
      application = Core::Application.create! valid_attributes
      get :index
      assigns(:core_applications).should eq([application])
    end
  end

  describe "GET show" do
    it "assigns the requested application as @application" do
      application = Core::Application.create! valid_attributes
      get :show, :id => application.id
      assigns(:core_application).should eq(application)
    end
  end

  describe "GET new" do
    it "assigns a new application as @application" do
      get :new
      assigns(:core_application).should be_a_new(Core::Application)
    end
  end

  describe "GET edit" do
    it "assigns the requested application as @application" do
      application = Core::Application.create! valid_attributes
      get :edit, :id => application.id
      assigns(:core_application).should eq(application)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Core::Application" do
        expect {
          post :create, :core_application => valid_attributes
        }.to change(Core::Application, :count).by(1)
      end

      it "assigns a newly created application as @application" do
        post :create, :core_application => valid_attributes
        assigns(:core_application).should be_a(Core::Application)
        assigns(:core_application).should be_persisted
      end

      it "redirects to the created application" do
        post :create, :core_application => valid_attributes
        response.should redirect_to(Core::Application.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved application as @application" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Application.any_instance.stub(:save).and_return(false)
        post :create, :core_application => {}
        assigns(:core_application).should be_a_new(Core::Application)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Application.any_instance.stub(:save).and_return(false)
        post :create, :core_application => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested application" do
        application = Core::Application.create! valid_attributes
        # Assuming there are no other core_applications in the database, this
        # specifies that the Core::Application created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Core::Application.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => application.id, :core_application => {'these' => 'params'}
      end

      it "assigns the requested application as @application" do
        application = Core::Application.create! valid_attributes
        put :update, :id => application.id, :core_application => valid_attributes
        assigns(:core_application).should eq(application)
      end

      it "redirects to the application" do
        application = Core::Application.create! valid_attributes
        put :update, :id => application.id, :core_application => valid_attributes
        response.should redirect_to(application)
      end
    end

    describe "with invalid params" do
      it "assigns the application as @application" do
        application = Core::Application.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Application.any_instance.stub(:save).and_return(false)
        put :update, :id => application.id, :core_application => {}
        assigns(:core_application).should eq(application)
      end

      it "re-renders the 'edit' template" do
        application = Core::Application.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Application.any_instance.stub(:save).and_return(false)
        put :update, :id => application.id, :core_application => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested application" do
      application = Core::Application.create! valid_attributes
      expect {
        delete :destroy, :id => application.id
      }.to change(Core::Application, :count).by(-1)
    end

    it "redirects to the core_applications list" do
      application = Core::Application.create! valid_attributes
      delete :destroy, :id => application.id
      response.should redirect_to(core_applications_url)
    end
  end

end
