require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Core::ReleasesController do

  # This should return the minimal set of attributes required to create a valid
  # Core::Release. As you add validations to Core::Release, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all core_releases as @core_releases" do
      release = Core::Release.create! valid_attributes
      get :index
      assigns(:core_releases).should eq([release])
    end
  end

  describe "GET show" do
    it "assigns the requested release as @release" do
      release = Core::Release.create! valid_attributes
      get :show, :id => release.id
      assigns(:release).should eq(release)
    end
  end

  describe "GET new" do
    it "assigns a new release as @release" do
      get :new
      assigns(:release).should be_a_new(Core::Release)
    end
  end

  describe "GET edit" do
    it "assigns the requested release as @release" do
      release = Core::Release.create! valid_attributes
      get :edit, :id => release.id
      assigns(:release).should eq(release)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Core::Release" do
        expect {
          post :create, :release => valid_attributes
        }.to change(Core::Release, :count).by(1)
      end

      it "assigns a newly created release as @release" do
        post :create, :release => valid_attributes
        assigns(:release).should be_a(Core::Release)
        assigns(:release).should be_persisted
      end

      it "redirects to the created release" do
        post :create, :release => valid_attributes
        response.should redirect_to(Core::Release.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved release as @release" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Release.any_instance.stub(:save).and_return(false)
        post :create, :release => {}
        assigns(:release).should be_a_new(Core::Release)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Release.any_instance.stub(:save).and_return(false)
        post :create, :release => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested release" do
        release = Core::Release.create! valid_attributes
        # Assuming there are no other core_releases in the database, this
        # specifies that the Core::Release created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Core::Release.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => release.id, :release => {'these' => 'params'}
      end

      it "assigns the requested release as @release" do
        release = Core::Release.create! valid_attributes
        put :update, :id => release.id, :release => valid_attributes
        assigns(:release).should eq(release)
      end

      it "redirects to the release" do
        release = Core::Release.create! valid_attributes
        put :update, :id => release.id, :release => valid_attributes
        response.should redirect_to(release)
      end
    end

    describe "with invalid params" do
      it "assigns the release as @release" do
        release = Core::Release.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Release.any_instance.stub(:save).and_return(false)
        put :update, :id => release.id, :release => {}
        assigns(:release).should eq(release)
      end

      it "re-renders the 'edit' template" do
        release = Core::Release.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Core::Release.any_instance.stub(:save).and_return(false)
        put :update, :id => release.id, :release => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested release" do
      release = Core::Release.create! valid_attributes
      expect {
        delete :destroy, :id => release.id
      }.to change(Core::Release, :count).by(-1)
    end

    it "redirects to the core_releases list" do
      release = Core::Release.create! valid_attributes
      delete :destroy, :id => release.id
      response.should redirect_to(core_releases_url)
    end
  end

end
