require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Pluto::EnvironmentVariablesController do

  # This should return the minimal set of attributes required to create a valid
  # Pluto::EnvironmentVariable. As you add validations to Pluto::EnvironmentVariable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pluto_environment_variables as @pluto_environment_variables" do
      environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
      get :index
      assigns(:pluto_environment_variables).should eq([environment_variable])
    end
  end

  describe "GET show" do
    it "assigns the requested environment_variable as @environment_variable" do
      environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
      get :show, :id => environment_variable.id
      assigns(:environment_variable).should eq(environment_variable)
    end
  end

  describe "GET new" do
    it "assigns a new environment_variable as @environment_variable" do
      get :new
      assigns(:environment_variable).should be_a_new(Pluto::EnvironmentVariable)
    end
  end

  describe "GET edit" do
    it "assigns the requested environment_variable as @environment_variable" do
      environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
      get :edit, :id => environment_variable.id
      assigns(:environment_variable).should eq(environment_variable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pluto::EnvironmentVariable" do
        expect {
          post :create, :environment_variable => valid_attributes
        }.to change(Pluto::EnvironmentVariable, :count).by(1)
      end

      it "assigns a newly created environment_variable as @environment_variable" do
        post :create, :environment_variable => valid_attributes
        assigns(:environment_variable).should be_a(Pluto::EnvironmentVariable)
        assigns(:environment_variable).should be_persisted
      end

      it "redirects to the created environment_variable" do
        post :create, :environment_variable => valid_attributes
        response.should redirect_to(Pluto::EnvironmentVariable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved environment_variable as @environment_variable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::EnvironmentVariable.any_instance.stub(:save).and_return(false)
        post :create, :environment_variable => {}
        assigns(:environment_variable).should be_a_new(Pluto::EnvironmentVariable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::EnvironmentVariable.any_instance.stub(:save).and_return(false)
        post :create, :environment_variable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested environment_variable" do
        environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
        # Assuming there are no other pluto_environment_variables in the database, this
        # specifies that the Pluto::EnvironmentVariable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pluto::EnvironmentVariable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => environment_variable.id, :environment_variable => {'these' => 'params'}
      end

      it "assigns the requested environment_variable as @environment_variable" do
        environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
        put :update, :id => environment_variable.id, :environment_variable => valid_attributes
        assigns(:environment_variable).should eq(environment_variable)
      end

      it "redirects to the environment_variable" do
        environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
        put :update, :id => environment_variable.id, :environment_variable => valid_attributes
        response.should redirect_to(environment_variable)
      end
    end

    describe "with invalid params" do
      it "assigns the environment_variable as @environment_variable" do
        environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::EnvironmentVariable.any_instance.stub(:save).and_return(false)
        put :update, :id => environment_variable.id, :environment_variable => {}
        assigns(:environment_variable).should eq(environment_variable)
      end

      it "re-renders the 'edit' template" do
        environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::EnvironmentVariable.any_instance.stub(:save).and_return(false)
        put :update, :id => environment_variable.id, :environment_variable => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested environment_variable" do
      environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
      expect {
        delete :destroy, :id => environment_variable.id
      }.to change(Pluto::EnvironmentVariable, :count).by(-1)
    end

    it "redirects to the pluto_environment_variables list" do
      environment_variable = Pluto::EnvironmentVariable.create! valid_attributes
      delete :destroy, :id => environment_variable.id
      response.should redirect_to(pluto_environment_variables_url)
    end
  end

end
