require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Pluto::ProcessInstancesController do

  # This should return the minimal set of attributes required to create a valid
  # Pluto::ProcessInstance. As you add validations to Pluto::ProcessInstance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Pluto::ProcessInstancesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pluto_process_instances as @pluto_process_instances" do
      process_instance = Pluto::ProcessInstance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pluto_process_instances).should eq([process_instance])
    end
  end

  describe "GET show" do
    it "assigns the requested process_instance as @process_instance" do
      process_instance = Pluto::ProcessInstance.create! valid_attributes
      get :show, {:id => process_instance.to_param}, valid_session
      assigns(:process_instance).should eq(process_instance)
    end
  end

  describe "GET new" do
    it "assigns a new process_instance as @process_instance" do
      get :new, {}, valid_session
      assigns(:process_instance).should be_a_new(Pluto::ProcessInstance)
    end
  end

  describe "GET edit" do
    it "assigns the requested process_instance as @process_instance" do
      process_instance = Pluto::ProcessInstance.create! valid_attributes
      get :edit, {:id => process_instance.to_param}, valid_session
      assigns(:process_instance).should eq(process_instance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pluto::ProcessInstance" do
        expect {
          post :create, {:process_instance => valid_attributes}, valid_session
        }.to change(Pluto::ProcessInstance, :count).by(1)
      end

      it "assigns a newly created process_instance as @process_instance" do
        post :create, {:process_instance => valid_attributes}, valid_session
        assigns(:process_instance).should be_a(Pluto::ProcessInstance)
        assigns(:process_instance).should be_persisted
      end

      it "redirects to the created process_instance" do
        post :create, {:process_instance => valid_attributes}, valid_session
        response.should redirect_to(Pluto::ProcessInstance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved process_instance as @process_instance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::ProcessInstance.any_instance.stub(:save).and_return(false)
        post :create, {:process_instance => {}}, valid_session
        assigns(:process_instance).should be_a_new(Pluto::ProcessInstance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::ProcessInstance.any_instance.stub(:save).and_return(false)
        post :create, {:process_instance => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested process_instance" do
        process_instance = Pluto::ProcessInstance.create! valid_attributes
        # Assuming there are no other pluto_process_instances in the database, this
        # specifies that the Pluto::ProcessInstance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pluto::ProcessInstance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => process_instance.to_param, :process_instance => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested process_instance as @process_instance" do
        process_instance = Pluto::ProcessInstance.create! valid_attributes
        put :update, {:id => process_instance.to_param, :process_instance => valid_attributes}, valid_session
        assigns(:process_instance).should eq(process_instance)
      end

      it "redirects to the process_instance" do
        process_instance = Pluto::ProcessInstance.create! valid_attributes
        put :update, {:id => process_instance.to_param, :process_instance => valid_attributes}, valid_session
        response.should redirect_to(process_instance)
      end
    end

    describe "with invalid params" do
      it "assigns the process_instance as @process_instance" do
        process_instance = Pluto::ProcessInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::ProcessInstance.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_instance.to_param, :process_instance => {}}, valid_session
        assigns(:process_instance).should eq(process_instance)
      end

      it "re-renders the 'edit' template" do
        process_instance = Pluto::ProcessInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pluto::ProcessInstance.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_instance.to_param, :process_instance => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested process_instance" do
      process_instance = Pluto::ProcessInstance.create! valid_attributes
      expect {
        delete :destroy, {:id => process_instance.to_param}, valid_session
      }.to change(Pluto::ProcessInstance, :count).by(-1)
    end

    it "redirects to the pluto_process_instances list" do
      process_instance = Pluto::ProcessInstance.create! valid_attributes
      delete :destroy, {:id => process_instance.to_param}, valid_session
      response.should redirect_to(pluto_process_instances_url)
    end
  end

end
