require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Http::PassersController do

  let(:machine)     { Core::Machine.create(host: 'example.com') }
  # This should return the minimal set of attributes required to create a valid
  # Http::Passer. As you add validations to Http::Passer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { port: 5000, core_machine_id: machine.id }
  end

  describe "GET index" do
    it "assigns all http_passers as @http_passers" do
      passer = Http::Passer.create! valid_attributes
      get :index
      assigns(:http_passers).should eq([passer])
    end
  end

  describe "GET show" do
    it "assigns the requested passer as @passer" do
      passer = Http::Passer.create! valid_attributes
      get :show, :id => passer.id
      assigns(:http_passer).should eq(passer)
    end
  end

  describe "GET new" do
    it "assigns a new passer as @passer" do
      get :new
      assigns(:http_passer).should be_a_new(Http::Passer)
    end
  end

  describe "GET edit" do
    it "assigns the requested passer as @passer" do
      passer = Http::Passer.create! valid_attributes
      get :edit, :id => passer.id
      assigns(:http_passer).should eq(passer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Http::Passer" do
        expect {
          post :create, :http_passer => valid_attributes
        }.to change(Http::Passer, :count).by(1)
      end

      it "assigns a newly created passer as @passer" do
        post :create, :http_passer => valid_attributes
        assigns(:http_passer).should be_a(Http::Passer)
        assigns(:http_passer).should be_persisted
      end

      it "redirects to the created passer" do
        post :create, :http_passer => valid_attributes
        response.should redirect_to(Http::Passer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passer as @passer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Passer.any_instance.stub(:save).and_return(false)
        post :create, :http_passer => {}
        assigns(:http_passer).should be_a_new(Http::Passer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Passer.any_instance.stub(:save).and_return(false)
        post :create, :http_passer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passer" do
        passer = Http::Passer.create! valid_attributes
        # Assuming there are no other http_passers in the database, this
        # specifies that the Http::Passer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Http::Passer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => passer.id, :http_passer => {'these' => 'params'}
      end

      it "assigns the requested passer as @passer" do
        passer = Http::Passer.create! valid_attributes
        put :update, :id => passer.id, :http_passer => valid_attributes
        assigns(:http_passer).should eq(passer)
      end

      it "redirects to the passer" do
        passer = Http::Passer.create! valid_attributes
        put :update, :id => passer.id, :http_passer => valid_attributes
        response.should redirect_to(passer)
      end
    end

    describe "with invalid params" do
      it "assigns the passer as @passer" do
        passer = Http::Passer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Passer.any_instance.stub(:save).and_return(false)
        put :update, :id => passer.id, :http_passer => {}
        assigns(:http_passer).should eq(passer)
      end

      it "re-renders the 'edit' template" do
        passer = Http::Passer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Passer.any_instance.stub(:save).and_return(false)
        put :update, :id => passer.id, :http_passer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passer" do
      passer = Http::Passer.create! valid_attributes
      expect {
        delete :destroy, :id => passer.id
      }.to change(Http::Passer, :count).by(-1)
    end

    it "redirects to the http_passers list" do
      passer = Http::Passer.create! valid_attributes
      delete :destroy, :id => passer.id
      response.should redirect_to(http_passers_url)
    end
  end

end
