require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Http::PathRulesController do

  let(:application) { Core::Application.create(name: 'client_example') }
  # This should return the minimal set of attributes required to create a valid
  # Http::PathRule. As you add validations to Http::PathRule, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { core_application_id: application.id, path: '/*', actions: '[["forward", "web"]]' }
  end

  describe "GET index" do
    it "assigns all http_path_rules as @http_path_rules" do
      path_rule = Http::PathRule.create! valid_attributes
      get :index
      assigns(:http_path_rules).should eq([path_rule])
    end
  end

  describe "GET show" do
    it "assigns the requested path_rule as @path_rule" do
      path_rule = Http::PathRule.create! valid_attributes
      get :show, :id => path_rule.id
      assigns(:http_path_rule).should eq(path_rule)
    end
  end

  describe "GET new" do
    it "assigns a new path_rule as @path_rule" do
      get :new
      assigns(:http_path_rule).should be_a_new(Http::PathRule)
    end
  end

  describe "GET edit" do
    it "assigns the requested path_rule as @path_rule" do
      path_rule = Http::PathRule.create! valid_attributes
      get :edit, :id => path_rule.id
      assigns(:http_path_rule).should eq(path_rule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Http::PathRule" do
        expect {
          post :create, :http_path_rule => valid_attributes
        }.to change(Http::PathRule, :count).by(1)
      end

      it "assigns a newly created path_rule as @path_rule" do
        post :create, :http_path_rule => valid_attributes
        assigns(:http_path_rule).should be_a(Http::PathRule)
        assigns(:http_path_rule).should be_persisted
      end

      it "redirects to the created path_rule" do
        post :create, :http_path_rule => valid_attributes
        response.should redirect_to(Http::PathRule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved path_rule as @path_rule" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::PathRule.any_instance.stub(:save).and_return(false)
        post :create, :http_path_rule => {}
        assigns(:http_path_rule).should be_a_new(Http::PathRule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::PathRule.any_instance.stub(:save).and_return(false)
        post :create, :http_path_rule => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested path_rule" do
        path_rule = Http::PathRule.create! valid_attributes
        # Assuming there are no other http_path_rules in the database, this
        # specifies that the Http::PathRule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Http::PathRule.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => path_rule.id, :http_path_rule => {'these' => 'params'}
      end

      it "assigns the requested path_rule as @path_rule" do
        path_rule = Http::PathRule.create! valid_attributes
        put :update, :id => path_rule.id, :http_path_rule => valid_attributes
        assigns(:http_path_rule).should eq(path_rule)
      end

      it "redirects to the path_rule" do
        path_rule = Http::PathRule.create! valid_attributes
        put :update, :id => path_rule.id, :http_path_rule => valid_attributes
        response.should redirect_to(path_rule)
      end
    end

    describe "with invalid params" do
      it "assigns the path_rule as @path_rule" do
        path_rule = Http::PathRule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::PathRule.any_instance.stub(:save).and_return(false)
        put :update, :id => path_rule.id, :http_path_rule => {}
        assigns(:http_path_rule).should eq(path_rule)
      end

      it "re-renders the 'edit' template" do
        path_rule = Http::PathRule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::PathRule.any_instance.stub(:save).and_return(false)
        put :update, :id => path_rule.id, :http_path_rule => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested path_rule" do
      path_rule = Http::PathRule.create! valid_attributes
      expect {
        delete :destroy, :id => path_rule.id
      }.to change(Http::PathRule, :count).by(-1)
    end

    it "redirects to the http_path_rules list" do
      path_rule = Http::PathRule.create! valid_attributes
      delete :destroy, :id => path_rule.id
      response.should redirect_to(http_path_rules_url)
    end
  end

end
