require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Http::RoutersController do

  let(:machine)     { Core::Machine.create(host: 'example.com') }
  # This should return the minimal set of attributes required to create a valid
  # Http::Router. As you add validations to Http::Router, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { port: 5000, core_machine_id: machine.id }
  end

  describe "GET index" do
    it "assigns all http_routers as @http_routers" do
      router = Http::Router.create! valid_attributes
      get :index
      assigns(:http_routers).should eq([router])
    end
  end

  describe "GET show" do
    it "assigns the requested router as @router" do
      router = Http::Router.create! valid_attributes
      get :show, :id => router.id
      assigns(:http_router).should eq(router)
    end
  end

  describe "GET new" do
    it "assigns a new router as @router" do
      get :new
      assigns(:http_router).should be_a_new(Http::Router)
    end
  end

  describe "GET edit" do
    it "assigns the requested router as @router" do
      router = Http::Router.create! valid_attributes
      get :edit, :id => router.id
      assigns(:http_router).should eq(router)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Http::Router" do
        expect {
          post :create, :http_router => valid_attributes
        }.to change(Http::Router, :count).by(1)
      end

      it "assigns a newly created router as @router" do
        post :create, :http_router => valid_attributes
        assigns(:http_router).should be_a(Http::Router)
        assigns(:http_router).should be_persisted
      end

      it "redirects to the created router" do
        post :create, :http_router => valid_attributes
        response.should redirect_to(Http::Router.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved router as @router" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Router.any_instance.stub(:save).and_return(false)
        post :create, :http_router => {}
        assigns(:http_router).should be_a_new(Http::Router)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Router.any_instance.stub(:save).and_return(false)
        post :create, :http_router => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested router" do
        router = Http::Router.create! valid_attributes
        # Assuming there are no other http_routers in the database, this
        # specifies that the Http::Router created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Http::Router.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => router.id, :http_router => {'these' => 'params'}
      end

      it "assigns the requested router as @router" do
        router = Http::Router.create! valid_attributes
        put :update, :id => router.id, :http_router => valid_attributes
        assigns(:http_router).should eq(router)
      end

      it "redirects to the router" do
        router = Http::Router.create! valid_attributes
        put :update, :id => router.id, :http_router => valid_attributes
        response.should redirect_to(router)
      end
    end

    describe "with invalid params" do
      it "assigns the router as @router" do
        router = Http::Router.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Router.any_instance.stub(:save).and_return(false)
        put :update, :id => router.id, :http_router => {}
        assigns(:http_router).should eq(router)
      end

      it "re-renders the 'edit' template" do
        router = Http::Router.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Http::Router.any_instance.stub(:save).and_return(false)
        put :update, :id => router.id, :http_router => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested router" do
      router = Http::Router.create! valid_attributes
      expect {
        delete :destroy, :id => router.id
      }.to change(Http::Router, :count).by(-1)
    end

    it "redirects to the http_routers list" do
      router = Http::Router.create! valid_attributes
      delete :destroy, :id => router.id
      response.should redirect_to(http_routers_url)
    end
  end

end
